/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subui;

import ctrl.helper;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mainui.Home;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;
import pojos.Item;
import pojos.User;

/**
 *
 * @author SCORFi3LD
 */
public class item extends javax.swing.JInternalFrame {

    /**
     * Creates new form item
     */
    Session ses = utils.HibernateUtil.getSessionFactory().openSession();
    helper help = new helper();
    User user = Home.getLogedUser();

    //variable on update
    int on_update = 0;
    int on_update_item_id = 0;

    public item() {
        initComponents();
        clear();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_item_commission = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_item_name = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_save1 = new javax.swing.JButton();
        txt_item_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Manage Items");
        setFrameIcon(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 184, 148));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Item");
        jLabel1.setOpaque(true);

        txt_item_commission.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_item_commission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_item_commissionActionPerformed(evt);
            }
        });
        txt_item_commission.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_item_commissionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_item_commissionKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Item Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Item Commission :");

        txt_item_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_item_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_item_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_item_nameKeyReleased(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_x24.png"))); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_save1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_x24.png"))); // NOI18N
        btn_save1.setText("CLEAR");
        btn_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save1ActionPerformed(evt);
            }
        });

        txt_item_price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_item_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_item_priceActionPerformed(evt);
            }
        });
        txt_item_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_item_priceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_item_priceKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Item Price :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_item_name))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 233, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_item_price, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_item_commission, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_item_price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_item_commission, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Commission RS.", "Price", "Added Date", "Added Time", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setBackground(new java.awt.Color(0, 184, 148));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item List");
        jLabel4.setOpaque(true);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_x24.png"))); // NOI18N
        jButton2.setText("Update Selected Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_x24.png"))); // NOI18N
        jButton3.setText("Delete Selected Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_x24.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_item_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_nameKeyReleased

    }//GEN-LAST:event_txt_item_nameKeyReleased

    private void txt_item_commissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_item_commissionActionPerformed

    }//GEN-LAST:event_txt_item_commissionActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        if (on_update == 0) {
            if (!txt_item_commission.getText().equals("") && !txt_item_name.getText().equals("") && !txt_item_price.getText().equals("")) {
                saveItem(txt_item_name.getText(), Double.parseDouble(txt_item_commission.getText()), Double.parseDouble(txt_item_price.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "Emty Data ! Please Retry.");
            }
        } else {
            updateItem(on_update_item_id);
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_item_commissionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_commissionKeyReleased

    }//GEN-LAST:event_txt_item_commissionKeyReleased

    private void txt_item_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_item_name.getText().equals("")) {
                txt_item_price.grabFocus();
            }
        }
    }//GEN-LAST:event_txt_item_nameKeyPressed

    private void txt_item_commissionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_commissionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (on_update == 0) {
                if (!txt_item_commission.getText().equals("")) {
                    saveItem(txt_item_name.getText(), Double.parseDouble(txt_item_commission.getText()), Double.parseDouble(txt_item_price.getText()));
                } else {
                    JOptionPane.showMessageDialog(this, "Emty Data ! Please Retry.");
                }
            } else {
                updateItem(on_update_item_id);
            }
        }
    }//GEN-LAST:event_txt_item_commissionKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item ?");
            if (option == 0) {
                on_update_item_id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                Transaction tr = ses.beginTransaction();
                Item item = (Item) ses.load(Item.class, on_update_item_id);
                item.setStatus(0);
                tr.commit();
                clear();
                loadDataToTable();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Plase Select Row From Table !");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save1ActionPerformed
        clear();
    }//GEN-LAST:event_btn_save1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clear();
        loadDataToTable();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            btn_save.setText("UPDATE");
            txt_item_name.grabFocus();
            on_update = 1;
            try {
                on_update_item_id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                txt_item_name.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                txt_item_commission.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                txt_item_price.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            } catch (Exception e) {
            }

        } else {
            JOptionPane.showMessageDialog(this, "Plase Select Row From Table !");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_item_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_item_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_item_priceActionPerformed

    private void txt_item_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_priceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_item_price.getText().equals("")) {
                txt_item_commission.grabFocus();
            }
        }
    }//GEN-LAST:event_txt_item_priceKeyPressed

    private void txt_item_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_priceKeyReleased

    }//GEN-LAST:event_txt_item_priceKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_save1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_item_commission;
    private javax.swing.JTextField txt_item_name;
    private javax.swing.JTextField txt_item_price;
    // End of variables declaration//GEN-END:variables

    private void updateItem(int Item_Id) {
        try {
            if (Item_Id > 0) {
                Transaction tr = ses.beginTransaction();
                Item item = (Item) ses.load(Item.class, Item_Id);
                if (!txt_item_name.getText().equals("")) {
                    item.setName(txt_item_name.getText());
                }
                if (!txt_item_commission.getText().equals("")) {
                    if (Double.parseDouble(txt_item_commission.getText()) > 0) {
                        item.setCommission(Double.parseDouble(txt_item_commission.getText()));
                    }

                }
                if (!txt_item_price.getText().equals("")) {
                    if (Double.parseDouble(txt_item_price.getText()) > 0) {
                        item.setPrice(Double.parseDouble(txt_item_price.getText()));
                    }

                }
                tr.commit();
                clear();
                loadDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Plase Select Row From Table !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Plase Select Row From Table !");
        }
    }

    private boolean saveItem(String Name, double Commission, double price) {
        boolean flag = false;
        if (!Name.equals("") && Commission >= 0) {
            try {
                Transaction tr = ses.beginTransaction();
                Item item = new Item();
                item.setName(Name);
                item.setCommission(Commission);
                item.setPrice(price);
                item.setAddedDate(help.getDate());
                item.setAddedTime(help.getTime());
                item.setUser(user);
                item.setStatus(1);
                ses.save(item);
                tr.commit();
                JOptionPane.showMessageDialog(this, "Item Saved !");
                loadDataToTable();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Emty Data ! Please Retry.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Emty Data ! Please Retry.");
        }

        return flag;
    }

    private void clear() {
        btn_save.setText("SAVE");
        txt_item_commission.setText("");
        txt_item_name.setText("");
        txt_item_price.setText("");
        txt_item_name.grabFocus();
        on_update = 0;
        on_update_item_id = 0;
    }

    private void loadDataToTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        Criteria cr = ses.createCriteria(Item.class);
        cr.add(Restrictions.eq("status", 1));
        List<Item> item_list = cr.list();
        for (Item it : item_list) {
            Vector v = new Vector();
            v.add(it.getItemId());
            v.add(it.getName());
            v.add(it.getCommission());
            v.add(it.getPrice());
            v.add(it.getAddedDate());
            v.add(it.getAddedTime());
            v.add(it.getUser().getName());
            dtm.addRow(v);
        }

    }
}
