package pojos;
// Generated Jun 7, 2020 5:09:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer itemId;
     private User user;
     private String name;
     private Double commission;
     private Double price;
     private String addedDate;
     private String addedTime;
     private Integer status;
     private Set wadiItemses = new HashSet(0);
     private Set saveWadiItemses = new HashSet(0);

    public Item() {
    }

	
    public Item(User user) {
        this.user = user;
    }
    public Item(User user, String name, Double commission, Double price, String addedDate, String addedTime, Integer status, Set wadiItemses, Set saveWadiItemses) {
       this.user = user;
       this.name = name;
       this.commission = commission;
       this.price = price;
       this.addedDate = addedDate;
       this.addedTime = addedTime;
       this.status = status;
       this.wadiItemses = wadiItemses;
       this.saveWadiItemses = saveWadiItemses;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getCommission() {
        return this.commission;
    }
    
    public void setCommission(Double commission) {
        this.commission = commission;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(String addedDate) {
        this.addedDate = addedDate;
    }
    public String getAddedTime() {
        return this.addedTime;
    }
    
    public void setAddedTime(String addedTime) {
        this.addedTime = addedTime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getWadiItemses() {
        return this.wadiItemses;
    }
    
    public void setWadiItemses(Set wadiItemses) {
        this.wadiItemses = wadiItemses;
    }
    public Set getSaveWadiItemses() {
        return this.saveWadiItemses;
    }
    
    public void setSaveWadiItemses(Set saveWadiItemses) {
        this.saveWadiItemses = saveWadiItemses;
    }




}


