package pojos;
// Generated May 31, 2020 12:13:55 AM by Hibernate Tools 4.3.1



/**
 * SaveWadiPayment generated by hbm2java
 */
public class SaveWadiPayment  implements java.io.Serializable {


     private Integer saveWadiPaymentId;
     private SaveWadiWorker saveWadiWorker;
     private Double amountTotal;
     private Integer status;

    public SaveWadiPayment() {
    }

	
    public SaveWadiPayment(SaveWadiWorker saveWadiWorker) {
        this.saveWadiWorker = saveWadiWorker;
    }
    public SaveWadiPayment(SaveWadiWorker saveWadiWorker, Double amountTotal, Integer status) {
       this.saveWadiWorker = saveWadiWorker;
       this.amountTotal = amountTotal;
       this.status = status;
    }
   
    public Integer getSaveWadiPaymentId() {
        return this.saveWadiPaymentId;
    }
    
    public void setSaveWadiPaymentId(Integer saveWadiPaymentId) {
        this.saveWadiPaymentId = saveWadiPaymentId;
    }
    public SaveWadiWorker getSaveWadiWorker() {
        return this.saveWadiWorker;
    }
    
    public void setSaveWadiWorker(SaveWadiWorker saveWadiWorker) {
        this.saveWadiWorker = saveWadiWorker;
    }
    public Double getAmountTotal() {
        return this.amountTotal;
    }
    
    public void setAmountTotal(Double amountTotal) {
        this.amountTotal = amountTotal;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


