package pojos;
// Generated Jun 2, 2020 11:01:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wadi generated by hbm2java
 */
public class Wadi  implements java.io.Serializable {


     private Integer wadiId;
     private User user;
     private String name;
     private String addedDate;
     private String addedTime;
     private Integer status;
     private Set wadiUsers = new HashSet(0);
     private Set saveWadis = new HashSet(0);

    public Wadi() {
    }

	
    public Wadi(User user) {
        this.user = user;
    }
    public Wadi(User user, String name, String addedDate, String addedTime, Integer status, Set wadiUsers, Set saveWadis) {
       this.user = user;
       this.name = name;
       this.addedDate = addedDate;
       this.addedTime = addedTime;
       this.status = status;
       this.wadiUsers = wadiUsers;
       this.saveWadis = saveWadis;
    }
   
    public Integer getWadiId() {
        return this.wadiId;
    }
    
    public void setWadiId(Integer wadiId) {
        this.wadiId = wadiId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(String addedDate) {
        this.addedDate = addedDate;
    }
    public String getAddedTime() {
        return this.addedTime;
    }
    
    public void setAddedTime(String addedTime) {
        this.addedTime = addedTime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getWadiUsers() {
        return this.wadiUsers;
    }
    
    public void setWadiUsers(Set wadiUsers) {
        this.wadiUsers = wadiUsers;
    }
    public Set getSaveWadis() {
        return this.saveWadis;
    }
    
    public void setSaveWadis(Set saveWadis) {
        this.saveWadis = saveWadis;
    }




}


