package pojos;
// Generated Jun 7, 2020 5:09:46 PM by Hibernate Tools 4.3.1



/**
 * WadiReturnLog generated by hbm2java
 */
public class WadiReturnLog  implements java.io.Serializable {


     private Integer wadiReturnLogId;
     private SaveWadiWorker saveWadiWorker;
     private Double returnCommission;

    public WadiReturnLog() {
    }

	
    public WadiReturnLog(SaveWadiWorker saveWadiWorker) {
        this.saveWadiWorker = saveWadiWorker;
    }
    public WadiReturnLog(SaveWadiWorker saveWadiWorker, Double returnCommission) {
       this.saveWadiWorker = saveWadiWorker;
       this.returnCommission = returnCommission;
    }
   
    public Integer getWadiReturnLogId() {
        return this.wadiReturnLogId;
    }
    
    public void setWadiReturnLogId(Integer wadiReturnLogId) {
        this.wadiReturnLogId = wadiReturnLogId;
    }
    public SaveWadiWorker getSaveWadiWorker() {
        return this.saveWadiWorker;
    }
    
    public void setSaveWadiWorker(SaveWadiWorker saveWadiWorker) {
        this.saveWadiWorker = saveWadiWorker;
    }
    public Double getReturnCommission() {
        return this.returnCommission;
    }
    
    public void setReturnCommission(Double returnCommission) {
        this.returnCommission = returnCommission;
    }




}


