package pojos;
// Generated Jun 7, 2020 5:09:46 PM by Hibernate Tools 4.3.1



/**
 * WadiReturn generated by hbm2java
 */
public class WadiReturn  implements java.io.Serializable {


     private Integer wadiReturnId;
     private SaveWadiItems saveWadiItems;
     private Wadi wadi;
     private Integer returnQty;
     private Double returnCommission;
     private Integer status;

    public WadiReturn() {
    }

	
    public WadiReturn(SaveWadiItems saveWadiItems, Wadi wadi) {
        this.saveWadiItems = saveWadiItems;
        this.wadi = wadi;
    }
    public WadiReturn(SaveWadiItems saveWadiItems, Wadi wadi, Integer returnQty, Double returnCommission, Integer status) {
       this.saveWadiItems = saveWadiItems;
       this.wadi = wadi;
       this.returnQty = returnQty;
       this.returnCommission = returnCommission;
       this.status = status;
    }
   
    public Integer getWadiReturnId() {
        return this.wadiReturnId;
    }
    
    public void setWadiReturnId(Integer wadiReturnId) {
        this.wadiReturnId = wadiReturnId;
    }
    public SaveWadiItems getSaveWadiItems() {
        return this.saveWadiItems;
    }
    
    public void setSaveWadiItems(SaveWadiItems saveWadiItems) {
        this.saveWadiItems = saveWadiItems;
    }
    public Wadi getWadi() {
        return this.wadi;
    }
    
    public void setWadi(Wadi wadi) {
        this.wadi = wadi;
    }
    public Integer getReturnQty() {
        return this.returnQty;
    }
    
    public void setReturnQty(Integer returnQty) {
        this.returnQty = returnQty;
    }
    public Double getReturnCommission() {
        return this.returnCommission;
    }
    
    public void setReturnCommission(Double returnCommission) {
        this.returnCommission = returnCommission;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


