package pojos;
// Generated Jun 3, 2020 2:21:40 PM by Hibernate Tools 4.3.1



/**
 * WorkerCommissionPay generated by hbm2java
 */
public class WorkerCommissionPay  implements java.io.Serializable {


     private Integer workerCommissionPayId;
     private User user;
     private Workers workers;
     private String payDate;
     private String payTime;
     private Double amount;
     private Integer status;

    public WorkerCommissionPay() {
    }

	
    public WorkerCommissionPay(User user, Workers workers) {
        this.user = user;
        this.workers = workers;
    }
    public WorkerCommissionPay(User user, Workers workers, String payDate, String payTime, Double amount, Integer status) {
       this.user = user;
       this.workers = workers;
       this.payDate = payDate;
       this.payTime = payTime;
       this.amount = amount;
       this.status = status;
    }
   
    public Integer getWorkerCommissionPayId() {
        return this.workerCommissionPayId;
    }
    
    public void setWorkerCommissionPayId(Integer workerCommissionPayId) {
        this.workerCommissionPayId = workerCommissionPayId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Workers getWorkers() {
        return this.workers;
    }
    
    public void setWorkers(Workers workers) {
        this.workers = workers;
    }
    public String getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }
    public String getPayTime() {
        return this.payTime;
    }
    
    public void setPayTime(String payTime) {
        this.payTime = payTime;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


